package demo.com.demorules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PsiData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "reading")
   private int reading;
   @org.kie.api.definition.type.Label(value = "timestamp")
   private java.util.Date timestamp;
   @org.kie.api.definition.type.Label(value = "status")
   private java.lang.String status;

   public PsiData()
   {
   }

   public int getReading()
   {
      return this.reading;
   }

   public void setReading(int reading)
   {
      this.reading = reading;
   }

   public java.util.Date getTimestamp()
   {
      return this.timestamp;
   }

   public void setTimestamp(java.util.Date timestamp)
   {
      this.timestamp = timestamp;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public PsiData(int reading, java.util.Date timestamp,
         java.lang.String status)
   {
      this.reading = reading;
      this.timestamp = timestamp;
      this.status = status;
   }

}