package demo.com.demorules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PsiData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PsiData() {
    }

}