package demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PsiData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "reading")
   private java.lang.Integer reading;
   @org.kie.api.definition.type.Label(value = "timestamp")
   private java.util.Date timestamp;

   public PsiData()
   {
   }

   public java.lang.Integer getReading()
   {
      return this.reading;
   }

   public void setReading(java.lang.Integer reading)
   {
      this.reading = reading;
   }

   public java.util.Date getTimestamp()
   {
      return this.timestamp;
   }

   public void setTimestamp(java.util.Date timestamp)
   {
      this.timestamp = timestamp;
   }

   public PsiData(java.lang.Integer reading, java.util.Date timestamp)
   {
      this.reading = reading;
      this.timestamp = timestamp;
   }

}